### ISSUE TITLE
go install does not contain package github.com/9oelM/elasticpwn/report/elasticpwn-backend

### ISSUE THREAD

**Issue by qwertymamba** [9oelM/elasticpwn#2]
Hello, I was able to successfully install elasticpwn using the command in the main page, but when I try to install elasticpwn-backend using the command I am getting this error.

 `C:\Users\qwerty>go install github.com/9oelM/elasticpwn/report/elasticpwn-backend@latest
go install: github.com/9oelM/elasticpwn/report/elasticpwn-backend@latest: module github.com/9oelM/elasticpwn@latest found (v0.1.2), but does not contain package github.com/9oelM/elasticpwn/report/elasticpwn-backend`

I am using a windows 10 machine with Go 1.17.5
How do I fix this?

**Comment by 9oelM** [comment]
Hey, thank you for filing this issue. I've confirmed it's not working for me too. I will work on the fix. Thanks.

**Comment by 9oelM** [comment]
In the meantime, if you want to use it right now before the fix, please manually clone the repository, and cd into `report/elasticpwn-backend`, run `go mod tidy`, and run `go build` to create the binary and use it.

**Comment by qwertymamba** [comment]
Thanks for the reply, I will manually install it. Thanks!

**Comment by 9oelM** [comment]
closed by #3
