### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [9oelM/elasticpwn#5]

**Comment by 9oelM** [comment]
hi @sasholy, did you try to write something more but couldn't for some reason?

**Comment by sasholy** [comment]
Hi
1. I have http://147.xxx.xxx.xxx:9200/
http://23.xxx.xxx.xxx:9200/
http://107.xxx.xxx.xxx:9200/
http://52.xxx.xxx.xxx:9200/ - list.txt

2. next -  elasticpwn elasticsearch -f my list.txt -of json -t 12 

is everything right?

thx.

**Comment by 9oelM** [comment]
That format should work.
